version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.flake
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        PROJECT_DIR: /workspace
    environment:
      PATH: /opt/ghc/bin:/home/user/.nix-profile/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin
    command: sleep infinity
    volumes:
      - .:/workspace:cached
      - nix:/nix
      - direnv-allow:/home/user/.local/share/direnv/allow
    security_opt:
      - label:disable
    network_mode: bridge

volumes:
  nix:
  direnv-allow: